# Experiment: Dropout

In [1]:
import torch
from torch import nn
from torch.utils.data import DataLoader

from torchvision import datasets
from torchvision.transforms import ToTensor

import matplotlib.pyplot as plt
import pandas as pd

import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

torch.manual_seed(42)

In [2]:
train_data = datasets.FashionMNIST(
    root="../data",
    train=True,
    download=True,
    transform=ToTensor(),
    target_transform=None
)

test_data = datasets.FashionMNIST(
    root="../data",
    train=False,
    download=True,
    transform=ToTensor(),
    target_transform=None
)

print(f"Length of train data: {len(train_data)}")
print(f"Length of test data: {len(test_data)}")

Length of train data: 60000
Length of test data: 10000

In [3]:
class_names = train_data.classes
print(class_names)

['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

In [4]:
BATCH_SIZE = 32

train_dataloader = DataLoader(
    dataset=train_data,
    batch_size=BATCH_SIZE,
    shuffle=True
)

test_dataloader = DataLoader(
    dataset=test_data,
    batch_size=BATCH_SIZE,
    shuffle=False
)

print(f"Length of train_dataloader: {len(train_dataloader)}, No. of images per batch: {BATCH_SIZE}")
print(f"Length of test_dataloader: {len(test_dataloader)}, No. of images per batch: {BATCH_SIZE}")

Length of train_dataloader: 1875, No. of images per batch: 32
Length of test_dataloader: 313, No. of images per batch: 32

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device : {device}")

Device : cuda

In [6]:
from torchmetrics import Accuracy, Precision, Recall, F1Score

train_metrics = {
    "accuracy": Accuracy(task="multiclass", num_classes=10).to(device),
    "precision": Precision(task="multiclass", num_classes=10, average="weighted").to(device),
    "recall": Recall(task="multiclass", num_classes=10, average="weighted").to(device),
    "f1": F1Score(task="multiclass", num_classes=10, average="weighted").to(device)
}

test_metrics = {
    "accuracy": Accuracy(task="multiclass", num_classes=10).to(device),
    "precision": Precision(task="multiclass", num_classes=10, average="weighted").to(device),
    "recall": Recall(task="multiclass", num_classes=10, average="weighted").to(device),
    "f1": F1Score(task="multiclass", num_classes=10, average="weighted").to(device)
}

exp_results = []

In [18]:
from src.models import CNN
from src.train import train_step, test_step

epochs = 20
history = {
    "train": [],
    "test": []
}

exp0 = CNN(dropout=0.0).to(device)

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(
    params=exp0.parameters(),
    lr=0.0005
)

for epoch in range(epochs):
    print(f"\nEpoch {epoch+1}/{epochs}")
    print("-"*30)

    train_results = train_step(
        model=exp0,
        dataloader=train_dataloader,
        loss_fn=loss_fn,
        optimizer=optimizer,
        metrics=train_metrics,
        device=device
    )

    test_results = test_step(
        model=exp0,
        dataloader=test_dataloader,
        loss_fn=loss_fn,
        metrics=test_metrics,
        device=device
    )

    history["train"].append(train_results)
    history["test"].append(test_results)

    print(
        f"Train Loss: {train_results['loss']:.4f} | "
        f"Train Acc: {train_results['accuracy']:.4f} | "
        f"Train Precision: {train_results['precision']:.4f} | "
        f"Train Recall: {train_results['recall']:.4f} | "
        f"Train F1: {train_results['f1']:.4f}"
    )

    print(
        f"Test Loss: {test_results['loss']:.4f} | "
        f"Test Acc: {test_results['accuracy']:.4f} | "
        f"Test Precision: {test_results['precision']:.4f} | "
        f"Test Recall: {test_results['recall']:.4f} | "
        f"Test F1: {test_results['f1']:.4f}"
    )

exp_results.append({
    "dropout": 0.0,
    "train_loss": history["train"][-1]["loss"],
    "test_loss": history["test"][-1]["loss"],
    "train_accuracy": history["train"][-1]["accuracy"],
    "test_accuracy": history["test"][-1]["accuracy"],
    "train_precision": history["train"][-1]["precision"],
    "test_precision": history["test"][-1]["precision"],
    "train_recall": history["train"][-1]["recall"],
    "test_recall": history["test"][-1]["recall"],
    "train_f1": history["train"][-1]["f1"],
    "test_f1": history["test"][-1]["f1"]
})

Epoch 1/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.4053 | Train Acc: 0.8556 | Train Precision: 0.8542 | Train Recall: 0.8556 | Train F1: 0.8546
Test Loss: 0.3224 | Test Acc: 0.8832 | Test Precision: 0.8882 | Test Recall: 0.8832 | Test F1: 0.8785

Epoch 2/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2534 | Train Acc: 0.9084 | Train Precision: 0.9080 | Train Recall: 0.9084 | Train F1: 0.9081
Test Loss: 0.2671 | Test Acc: 0.9037 | Test Precision: 0.9062 | Test Recall: 0.9037 | Test F1: 0.9044

Epoch 3/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2037 | Train Acc: 0.9245 | Train Precision: 0.9242 | Train Recall: 0.9245 | Train F1: 0.9243
Test Loss: 0.2329 | Test Acc: 0.9155 | Test Precision: 0.9162 | Test Recall: 0.9155 | Test F1: 0.9157

Epoch 4/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1650 | Train Acc: 0.9393 | Train Precision: 0.9391 | Train Recall: 0.9393 | Train F1: 0.9391
Test Loss: 0.2270 | Test Acc: 0.9198 | Test Precision: 0.9205 | Test Recall: 0.9198 | Test F1: 0.9197

Epoch 5/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1351 | Train Acc: 0.9509 | Train Precision: 0.9507 | Train Recall: 0.9509 | Train F1: 0.9508
Test Loss: 0.2325 | Test Acc: 0.9200 | Test Precision: 0.9218 | Test Recall: 0.9200 | Test F1: 0.9200

Epoch 6/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1051 | Train Acc: 0.9612 | Train Precision: 0.9611 | Train Recall: 0.9612 | Train F1: 0.9611
Test Loss: 0.2410 | Test Acc: 0.9251 | Test Precision: 0.9265 | Test Recall: 0.9251 | Test F1: 0.9255

Epoch 7/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0794 | Train Acc: 0.9716 | Train Precision: 0.9716 | Train Recall: 0.9716 | Train F1: 0.9716
Test Loss: 0.2580 | Test Acc: 0.9243 | Test Precision: 0.9251 | Test Recall: 0.9243 | Test F1: 0.9245

Epoch 8/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0612 | Train Acc: 0.9779 | Train Precision: 0.9778 | Train Recall: 0.9778 | Train F1: 0.9778
Test Loss: 0.2773 | Test Acc: 0.9214 | Test Precision: 0.9222 | Test Recall: 0.9214 | Test F1: 0.9209

Epoch 9/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0471 | Train Acc: 0.9831 | Train Precision: 0.9831 | Train Recall: 0.9831 | Train F1: 0.9831
Test Loss: 0.2790 | Test Acc: 0.9279 | Test Precision: 0.9294 | Test Recall: 0.9279 | Test F1: 0.9283

Epoch 10/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0337 | Train Acc: 0.9884 | Train Precision: 0.9884 | Train Recall: 0.9884 | Train F1: 0.9884
Test Loss: 0.3279 | Test Acc: 0.9254 | Test Precision: 0.9264 | Test Recall: 0.9254 | Test F1: 0.9256

Epoch 11/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0267 | Train Acc: 0.9910 | Train Precision: 0.9910 | Train Recall: 0.9910 | Train F1: 0.9910
Test Loss: 0.3625 | Test Acc: 0.9246 | Test Precision: 0.9260 | Test Recall: 0.9246 | Test F1: 0.9250

Epoch 12/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0215 | Train Acc: 0.9925 | Train Precision: 0.9925 | Train Recall: 0.9925 | Train F1: 0.9925
Test Loss: 0.4156 | Test Acc: 0.9174 | Test Precision: 0.9197 | Test Recall: 0.9174 | Test F1: 0.9165

Epoch 13/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0172 | Train Acc: 0.9945 | Train Precision: 0.9945 | Train Recall: 0.9945 | Train F1: 0.9945
Test Loss: 0.3972 | Test Acc: 0.9221 | Test Precision: 0.9223 | Test Recall: 0.9221 | Test F1: 0.9220

Epoch 14/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0158 | Train Acc: 0.9948 | Train Precision: 0.9948 | Train Recall: 0.9948 | Train F1: 0.9948
Test Loss: 0.4338 | Test Acc: 0.9240 | Test Precision: 0.9240 | Test Recall: 0.9240 | Test F1: 0.9236

Epoch 15/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0135 | Train Acc: 0.9954 | Train Precision: 0.9954 | Train Recall: 0.9954 | Train F1: 0.9954
Test Loss: 0.4513 | Test Acc: 0.9230 | Test Precision: 0.9244 | Test Recall: 0.9230 | Test F1: 0.9233

Epoch 16/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0108 | Train Acc: 0.9967 | Train Precision: 0.9967 | Train Recall: 0.9967 | Train F1: 0.9967
Test Loss: 0.4598 | Test Acc: 0.9233 | Test Precision: 0.9243 | Test Recall: 0.9233 | Test F1: 0.9233

Epoch 17/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0118 | Train Acc: 0.9962 | Train Precision: 0.9962 | Train Recall: 0.9962 | Train F1: 0.9962
Test Loss: 0.4836 | Test Acc: 0.9243 | Test Precision: 0.9243 | Test Recall: 0.9243 | Test F1: 0.9242

Epoch 18/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0099 | Train Acc: 0.9966 | Train Precision: 0.9966 | Train Recall: 0.9966 | Train F1: 0.9966
Test Loss: 0.4979 | Test Acc: 0.9232 | Test Precision: 0.9240 | Test Recall: 0.9232 | Test F1: 0.9233

Epoch 19/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0098 | Train Acc: 0.9966 | Train Precision: 0.9966 | Train Recall: 0.9966 | Train F1: 0.9966
Test Loss: 0.5248 | Test Acc: 0.9234 | Test Precision: 0.9235 | Test Recall: 0.9234 | Test F1: 0.9233

Epoch 20/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0081 | Train Acc: 0.9971 | Train Precision: 0.9971 | Train Recall: 0.9971 | Train F1: 0.9971
Test Loss: 0.5417 | Test Acc: 0.9227 | Test Precision: 0.9235 | Test Recall: 0.9227 | Test F1: 0.9230

In [7]:
from src.models import CNN
from src.train import train_step, test_step

epochs = 20
history = {
    "train": [],
    "test": []
}

exp1 = CNN(dropout=0.2).to(device)

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(
    params=exp1.parameters(),
    lr=0.0005
)

for epoch in range(epochs):
    print(f"\nEpoch {epoch+1}/{epochs}")
    print("-"*30)

    train_results = train_step(
        model=exp1,
        dataloader=train_dataloader,
        loss_fn=loss_fn,
        optimizer=optimizer,
        metrics=train_metrics,
        device=device
    )

    test_results = test_step(
        model=exp1,
        dataloader=test_dataloader,
        loss_fn=loss_fn,
        metrics=test_metrics,
        device=device
    )

    history["train"].append(train_results)
    history["test"].append(test_results)

    print(
        f"Train Loss: {train_results['loss']:.4f} | "
        f"Train Acc: {train_results['accuracy']:.4f} | "
        f"Train Precision: {train_results['precision']:.4f} | "
        f"Train Recall: {train_results['recall']:.4f} | "
        f"Train F1: {train_results['f1']:.4f}"
    )

    print(
        f"Test Loss: {test_results['loss']:.4f} | "
        f"Test Acc: {test_results['accuracy']:.4f} | "
        f"Test Precision: {test_results['precision']:.4f} | "
        f"Test Recall: {test_results['recall']:.4f} | "
        f"Test F1: {test_results['f1']:.4f}"
    )

exp_results.append({
    "dropout": 0.2,
    "train_loss": history["train"][-1]["loss"],
    "test_loss": history["test"][-1]["loss"],
    "train_accuracy": history["train"][-1]["accuracy"],
    "test_accuracy": history["test"][-1]["accuracy"],
    "train_precision": history["train"][-1]["precision"],
    "test_precision": history["test"][-1]["precision"],
    "train_recall": history["train"][-1]["recall"],
    "test_recall": history["test"][-1]["recall"],
    "train_f1": history["train"][-1]["f1"],
    "test_f1": history["test"][-1]["f1"]
})

Epoch 1/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.4402 | Train Acc: 0.8414 | Train Precision: 0.8397 | Train Recall: 0.8414 | Train F1: 0.8402
Test Loss: 0.3339 | Test Acc: 0.8805 | Test Precision: 0.8839 | Test Recall: 0.8805 | Test F1: 0.8774

Epoch 2/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2811 | Train Acc: 0.8967 | Train Precision: 0.8962 | Train Recall: 0.8966 | Train F1: 0.8963
Test Loss: 0.2672 | Test Acc: 0.9032 | Test Precision: 0.9029 | Test Recall: 0.9032 | Test F1: 0.9027

Epoch 3/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2360 | Train Acc: 0.9130 | Train Precision: 0.9126 | Train Recall: 0.9130 | Train F1: 0.9128
Test Loss: 0.2500 | Test Acc: 0.9076 | Test Precision: 0.9106 | Test Recall: 0.9076 | Test F1: 0.9082

Epoch 4/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2023 | Train Acc: 0.9261 | Train Precision: 0.9258 | Train Recall: 0.9261 | Train F1: 0.9259
Test Loss: 0.2332 | Test Acc: 0.9167 | Test Precision: 0.9187 | Test Recall: 0.9167 | Test F1: 0.9170

Epoch 5/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1760 | Train Acc: 0.9350 | Train Precision: 0.9348 | Train Recall: 0.9350 | Train F1: 0.9349
Test Loss: 0.2183 | Test Acc: 0.9241 | Test Precision: 0.9238 | Test Recall: 0.9241 | Test F1: 0.9234

Epoch 6/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1500 | Train Acc: 0.9439 | Train Precision: 0.9437 | Train Recall: 0.9439 | Train F1: 0.9438
Test Loss: 0.2341 | Test Acc: 0.9222 | Test Precision: 0.9226 | Test Recall: 0.9222 | Test F1: 0.9222

Epoch 7/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1312 | Train Acc: 0.9511 | Train Precision: 0.9509 | Train Recall: 0.9511 | Train F1: 0.9510
Test Loss: 0.2228 | Test Acc: 0.9274 | Test Precision: 0.9279 | Test Recall: 0.9274 | Test F1: 0.9276

Epoch 8/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1120 | Train Acc: 0.9582 | Train Precision: 0.9581 | Train Recall: 0.9582 | Train F1: 0.9581
Test Loss: 0.2386 | Test Acc: 0.9224 | Test Precision: 0.9235 | Test Recall: 0.9224 | Test F1: 0.9224

Epoch 9/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0965 | Train Acc: 0.9635 | Train Precision: 0.9635 | Train Recall: 0.9635 | Train F1: 0.9635
Test Loss: 0.2352 | Test Acc: 0.9277 | Test Precision: 0.9277 | Test Recall: 0.9277 | Test F1: 0.9274

Epoch 10/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0817 | Train Acc: 0.9695 | Train Precision: 0.9694 | Train Recall: 0.9695 | Train F1: 0.9694
Test Loss: 0.2633 | Test Acc: 0.9261 | Test Precision: 0.9270 | Test Recall: 0.9261 | Test F1: 0.9264

Epoch 11/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0714 | Train Acc: 0.9735 | Train Precision: 0.9735 | Train Recall: 0.9735 | Train F1: 0.9735
Test Loss: 0.2720 | Test Acc: 0.9257 | Test Precision: 0.9256 | Test Recall: 0.9257 | Test F1: 0.9248

Epoch 12/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0610 | Train Acc: 0.9773 | Train Precision: 0.9773 | Train Recall: 0.9773 | Train F1: 0.9773
Test Loss: 0.2743 | Test Acc: 0.9278 | Test Precision: 0.9274 | Test Recall: 0.9278 | Test F1: 0.9272

Epoch 13/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0549 | Train Acc: 0.9797 | Train Precision: 0.9797 | Train Recall: 0.9797 | Train F1: 0.9797
Test Loss: 0.2902 | Test Acc: 0.9285 | Test Precision: 0.9288 | Test Recall: 0.9285 | Test F1: 0.9284

Epoch 14/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0476 | Train Acc: 0.9823 | Train Precision: 0.9823 | Train Recall: 0.9823 | Train F1: 0.9823
Test Loss: 0.2923 | Test Acc: 0.9289 | Test Precision: 0.9291 | Test Recall: 0.9289 | Test F1: 0.9289

Epoch 15/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0442 | Train Acc: 0.9833 | Train Precision: 0.9833 | Train Recall: 0.9833 | Train F1: 0.9833
Test Loss: 0.3215 | Test Acc: 0.9302 | Test Precision: 0.9299 | Test Recall: 0.9302 | Test F1: 0.9298

Epoch 16/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0376 | Train Acc: 0.9860 | Train Precision: 0.9860 | Train Recall: 0.9860 | Train F1: 0.9860
Test Loss: 0.3531 | Test Acc: 0.9279 | Test Precision: 0.9286 | Test Recall: 0.9279 | Test F1: 0.9282

Epoch 17/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0351 | Train Acc: 0.9873 | Train Precision: 0.9873 | Train Recall: 0.9873 | Train F1: 0.9873
Test Loss: 0.3564 | Test Acc: 0.9293 | Test Precision: 0.9293 | Test Recall: 0.9293 | Test F1: 0.9292

Epoch 18/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0328 | Train Acc: 0.9881 | Train Precision: 0.9881 | Train Recall: 0.9881 | Train F1: 0.9881
Test Loss: 0.3567 | Test Acc: 0.9304 | Test Precision: 0.9308 | Test Recall: 0.9304 | Test F1: 0.9304

Epoch 19/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0303 | Train Acc: 0.9889 | Train Precision: 0.9889 | Train Recall: 0.9889 | Train F1: 0.9889
Test Loss: 0.3793 | Test Acc: 0.9264 | Test Precision: 0.9266 | Test Recall: 0.9264 | Test F1: 0.9263

Epoch 20/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0287 | Train Acc: 0.9892 | Train Precision: 0.9892 | Train Recall: 0.9892 | Train F1: 0.9892
Test Loss: 0.4138 | Test Acc: 0.9270 | Test Precision: 0.9270 | Test Recall: 0.9270 | Test F1: 0.9268

In [8]:
from src.models import CNN
from src.train import train_step, test_step

epochs = 20
history = {
    "train": [],
    "test": []
}

exp2 = CNN(dropout=0.4).to(device)

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(
    params=exp2.parameters(),
    lr=0.0005
)

for epoch in range(epochs):
    print(f"\nEpoch {epoch+1}/{epochs}")
    print("-"*30)

    train_results = train_step(
        model=exp2,
        dataloader=train_dataloader,
        loss_fn=loss_fn,
        optimizer=optimizer,
        metrics=train_metrics,
        device=device
    )

    test_results = test_step(
        model=exp2,
        dataloader=test_dataloader,
        loss_fn=loss_fn,
        metrics=test_metrics,
        device=device
    )

    history["train"].append(train_results)
    history["test"].append(test_results)

    print(
        f"Train Loss: {train_results['loss']:.4f} | "
        f"Train Acc: {train_results['accuracy']:.4f} | "
        f"Train Precision: {train_results['precision']:.4f} | "
        f"Train Recall: {train_results['recall']:.4f} | "
        f"Train F1: {train_results['f1']:.4f}"
    )

    print(
        f"Test Loss: {test_results['loss']:.4f} | "
        f"Test Acc: {test_results['accuracy']:.4f} | "
        f"Test Precision: {test_results['precision']:.4f} | "
        f"Test Recall: {test_results['recall']:.4f} | "
        f"Test F1: {test_results['f1']:.4f}"
    )

exp_results.append({
    "dropout": 0.4,
    "train_loss": history["train"][-1]["loss"],
    "test_loss": history["test"][-1]["loss"],
    "train_accuracy": history["train"][-1]["accuracy"],
    "test_accuracy": history["test"][-1]["accuracy"],
    "train_precision": history["train"][-1]["precision"],
    "test_precision": history["test"][-1]["precision"],
    "train_recall": history["train"][-1]["recall"],
    "test_recall": history["test"][-1]["recall"],
    "train_f1": history["train"][-1]["f1"],
    "test_f1": history["test"][-1]["f1"]
})

Epoch 1/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.4833 | Train Acc: 0.8266 | Train Precision: 0.8245 | Train Recall: 0.8266 | Train F1: 0.8249
Test Loss: 0.3162 | Test Acc: 0.8852 | Test Precision: 0.8851 | Test Recall: 0.8852 | Test F1: 0.8846

Epoch 2/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.3201 | Train Acc: 0.8847 | Train Precision: 0.8840 | Train Recall: 0.8847 | Train F1: 0.8842
Test Loss: 0.2782 | Test Acc: 0.9001 | Test Precision: 0.9005 | Test Recall: 0.9001 | Test F1: 0.8981

Epoch 3/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2700 | Train Acc: 0.9021 | Train Precision: 0.9015 | Train Recall: 0.9021 | Train F1: 0.9017
Test Loss: 0.2524 | Test Acc: 0.9075 | Test Precision: 0.9076 | Test Recall: 0.9075 | Test F1: 0.9070

Epoch 4/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2373 | Train Acc: 0.9129 | Train Precision: 0.9125 | Train Recall: 0.9129 | Train F1: 0.9126
Test Loss: 0.2385 | Test Acc: 0.9144 | Test Precision: 0.9149 | Test Recall: 0.9144 | Test F1: 0.9134

Epoch 5/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2125 | Train Acc: 0.9223 | Train Precision: 0.9220 | Train Recall: 0.9223 | Train F1: 0.9221
Test Loss: 0.2396 | Test Acc: 0.9134 | Test Precision: 0.9141 | Test Recall: 0.9134 | Test F1: 0.9125

Epoch 6/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1864 | Train Acc: 0.9308 | Train Precision: 0.9304 | Train Recall: 0.9308 | Train F1: 0.9305
Test Loss: 0.2182 | Test Acc: 0.9243 | Test Precision: 0.9240 | Test Recall: 0.9243 | Test F1: 0.9239

Epoch 7/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1656 | Train Acc: 0.9390 | Train Precision: 0.9387 | Train Recall: 0.9390 | Train F1: 0.9388
Test Loss: 0.2260 | Test Acc: 0.9229 | Test Precision: 0.9229 | Test Recall: 0.9229 | Test F1: 0.9225

Epoch 8/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1526 | Train Acc: 0.9438 | Train Precision: 0.9436 | Train Recall: 0.9438 | Train F1: 0.9437
Test Loss: 0.2359 | Test Acc: 0.9223 | Test Precision: 0.9224 | Test Recall: 0.9223 | Test F1: 0.9220

Epoch 9/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1363 | Train Acc: 0.9502 | Train Precision: 0.9500 | Train Recall: 0.9502 | Train F1: 0.9500
Test Loss: 0.2244 | Test Acc: 0.9245 | Test Precision: 0.9256 | Test Recall: 0.9245 | Test F1: 0.9247

Epoch 10/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1214 | Train Acc: 0.9544 | Train Precision: 0.9542 | Train Recall: 0.9544 | Train F1: 0.9543
Test Loss: 0.2473 | Test Acc: 0.9253 | Test Precision: 0.9248 | Test Recall: 0.9253 | Test F1: 0.9248

Epoch 11/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1113 | Train Acc: 0.9582 | Train Precision: 0.9581 | Train Recall: 0.9582 | Train F1: 0.9582
Test Loss: 0.2373 | Test Acc: 0.9242 | Test Precision: 0.9255 | Test Recall: 0.9242 | Test F1: 0.9246

Epoch 12/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0984 | Train Acc: 0.9633 | Train Precision: 0.9632 | Train Recall: 0.9633 | Train F1: 0.9632
Test Loss: 0.2371 | Test Acc: 0.9247 | Test Precision: 0.9246 | Test Recall: 0.9247 | Test F1: 0.9246

Epoch 13/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0904 | Train Acc: 0.9658 | Train Precision: 0.9657 | Train Recall: 0.9658 | Train F1: 0.9657
Test Loss: 0.2583 | Test Acc: 0.9264 | Test Precision: 0.9267 | Test Recall: 0.9264 | Test F1: 0.9264

Epoch 14/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0843 | Train Acc: 0.9682 | Train Precision: 0.9681 | Train Recall: 0.9682 | Train F1: 0.9681
Test Loss: 0.2603 | Test Acc: 0.9264 | Test Precision: 0.9265 | Test Recall: 0.9264 | Test F1: 0.9263

Epoch 15/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0766 | Train Acc: 0.9708 | Train Precision: 0.9708 | Train Recall: 0.9708 | Train F1: 0.9708
Test Loss: 0.2703 | Test Acc: 0.9285 | Test Precision: 0.9284 | Test Recall: 0.9285 | Test F1: 0.9283

Epoch 16/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0688 | Train Acc: 0.9741 | Train Precision: 0.9740 | Train Recall: 0.9741 | Train F1: 0.9740
Test Loss: 0.2981 | Test Acc: 0.9271 | Test Precision: 0.9273 | Test Recall: 0.9271 | Test F1: 0.9265

Epoch 17/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0657 | Train Acc: 0.9751 | Train Precision: 0.9751 | Train Recall: 0.9751 | Train F1: 0.9751
Test Loss: 0.2972 | Test Acc: 0.9283 | Test Precision: 0.9283 | Test Recall: 0.9283 | Test F1: 0.9282

Epoch 18/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0629 | Train Acc: 0.9766 | Train Precision: 0.9766 | Train Recall: 0.9766 | Train F1: 0.9766
Test Loss: 0.2936 | Test Acc: 0.9272 | Test Precision: 0.9281 | Test Recall: 0.9272 | Test F1: 0.9275

Epoch 19/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0583 | Train Acc: 0.9778 | Train Precision: 0.9778 | Train Recall: 0.9778 | Train F1: 0.9778
Test Loss: 0.3510 | Test Acc: 0.9238 | Test Precision: 0.9251 | Test Recall: 0.9238 | Test F1: 0.9235

Epoch 20/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0546 | Train Acc: 0.9785 | Train Precision: 0.9785 | Train Recall: 0.9785 | Train F1: 0.9785
Test Loss: 0.3217 | Test Acc: 0.9275 | Test Precision: 0.9275 | Test Recall: 0.9275 | Test F1: 0.9274

In [9]:
from src.models import CNN
from src.train import train_step, test_step

epochs = 20
history = {
    "train": [],
    "test": []
}

exp3 = CNN(dropout=0.5).to(device)

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(
    params=exp3.parameters(),
    lr=0.0005
)

for epoch in range(epochs):
    print(f"\nEpoch {epoch+1}/{epochs}")
    print("-"*30)

    train_results = train_step(
        model=exp3,
        dataloader=train_dataloader,
        loss_fn=loss_fn,
        optimizer=optimizer,
        metrics=train_metrics,
        device=device
    )

    test_results = test_step(
        model=exp3,
        dataloader=test_dataloader,
        loss_fn=loss_fn,
        metrics=test_metrics,
        device=device
    )

    history["train"].append(train_results)
    history["test"].append(test_results)

    print(
        f"Train Loss: {train_results['loss']:.4f} | "
        f"Train Acc: {train_results['accuracy']:.4f} | "
        f"Train Precision: {train_results['precision']:.4f} | "
        f"Train Recall: {train_results['recall']:.4f} | "
        f"Train F1: {train_results['f1']:.4f}"
    )

    print(
        f"Test Loss: {test_results['loss']:.4f} | "
        f"Test Acc: {test_results['accuracy']:.4f} | "
        f"Test Precision: {test_results['precision']:.4f} | "
        f"Test Recall: {test_results['recall']:.4f} | "
        f"Test F1: {test_results['f1']:.4f}"
    )

exp_results.append({
    "dropout": 0.5,
    "train_loss": history["train"][-1]["loss"],
    "test_loss": history["test"][-1]["loss"],
    "train_accuracy": history["train"][-1]["accuracy"],
    "test_accuracy": history["test"][-1]["accuracy"],
    "train_precision": history["train"][-1]["precision"],
    "test_precision": history["test"][-1]["precision"],
    "train_recall": history["train"][-1]["recall"],
    "test_recall": history["test"][-1]["recall"],
    "train_f1": history["train"][-1]["f1"],
    "test_f1": history["test"][-1]["f1"]
})

Epoch 1/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.4893 | Train Acc: 0.8272 | Train Precision: 0.8251 | Train Recall: 0.8272 | Train F1: 0.8258
Test Loss: 0.3130 | Test Acc: 0.8858 | Test Precision: 0.8877 | Test Recall: 0.8858 | Test F1: 0.8862

Epoch 2/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.3200 | Train Acc: 0.8864 | Train Precision: 0.8856 | Train Recall: 0.8864 | Train F1: 0.8858
Test Loss: 0.2667 | Test Acc: 0.9025 | Test Precision: 0.9029 | Test Recall: 0.9025 | Test F1: 0.9020

Epoch 3/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2724 | Train Acc: 0.9013 | Train Precision: 0.9008 | Train Recall: 0.9013 | Train F1: 0.9009
Test Loss: 0.2491 | Test Acc: 0.9101 | Test Precision: 0.9110 | Test Recall: 0.9101 | Test F1: 0.9104

Epoch 4/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2369 | Train Acc: 0.9128 | Train Precision: 0.9124 | Train Recall: 0.9128 | Train F1: 0.9125
Test Loss: 0.2385 | Test Acc: 0.9141 | Test Precision: 0.9141 | Test Recall: 0.9141 | Test F1: 0.9133

Epoch 5/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2098 | Train Acc: 0.9238 | Train Precision: 0.9236 | Train Recall: 0.9238 | Train F1: 0.9237
Test Loss: 0.2167 | Test Acc: 0.9237 | Test Precision: 0.9234 | Test Recall: 0.9237 | Test F1: 0.9234

Epoch 6/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1885 | Train Acc: 0.9304 | Train Precision: 0.9303 | Train Recall: 0.9304 | Train F1: 0.9303
Test Loss: 0.2196 | Test Acc: 0.9223 | Test Precision: 0.9230 | Test Recall: 0.9223 | Test F1: 0.9224

Epoch 7/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1679 | Train Acc: 0.9387 | Train Precision: 0.9385 | Train Recall: 0.9387 | Train F1: 0.9385
Test Loss: 0.2287 | Test Acc: 0.9243 | Test Precision: 0.9242 | Test Recall: 0.9243 | Test F1: 0.9233

Epoch 8/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1535 | Train Acc: 0.9427 | Train Precision: 0.9426 | Train Recall: 0.9427 | Train F1: 0.9427
Test Loss: 0.2161 | Test Acc: 0.9275 | Test Precision: 0.9272 | Test Recall: 0.9275 | Test F1: 0.9270

Epoch 9/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1380 | Train Acc: 0.9485 | Train Precision: 0.9484 | Train Recall: 0.9485 | Train F1: 0.9484
Test Loss: 0.2166 | Test Acc: 0.9291 | Test Precision: 0.9291 | Test Recall: 0.9291 | Test F1: 0.9290

Epoch 10/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1232 | Train Acc: 0.9539 | Train Precision: 0.9538 | Train Recall: 0.9539 | Train F1: 0.9539
Test Loss: 0.2212 | Test Acc: 0.9276 | Test Precision: 0.9276 | Test Recall: 0.9276 | Test F1: 0.9273

Epoch 11/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1129 | Train Acc: 0.9573 | Train Precision: 0.9572 | Train Recall: 0.9573 | Train F1: 0.9573
Test Loss: 0.2583 | Test Acc: 0.9243 | Test Precision: 0.9244 | Test Recall: 0.9243 | Test F1: 0.9237

Epoch 12/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1006 | Train Acc: 0.9614 | Train Precision: 0.9614 | Train Recall: 0.9614 | Train F1: 0.9614
Test Loss: 0.2463 | Test Acc: 0.9276 | Test Precision: 0.9277 | Test Recall: 0.9276 | Test F1: 0.9266

Epoch 13/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0935 | Train Acc: 0.9642 | Train Precision: 0.9641 | Train Recall: 0.9642 | Train F1: 0.9641
Test Loss: 0.2570 | Test Acc: 0.9262 | Test Precision: 0.9263 | Test Recall: 0.9262 | Test F1: 0.9255

Epoch 14/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0875 | Train Acc: 0.9667 | Train Precision: 0.9667 | Train Recall: 0.9667 | Train F1: 0.9667
Test Loss: 0.2503 | Test Acc: 0.9281 | Test Precision: 0.9292 | Test Recall: 0.9281 | Test F1: 0.9283

Epoch 15/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0789 | Train Acc: 0.9695 | Train Precision: 0.9695 | Train Recall: 0.9695 | Train F1: 0.9695
Test Loss: 0.2539 | Test Acc: 0.9332 | Test Precision: 0.9330 | Test Recall: 0.9332 | Test F1: 0.9329

Epoch 16/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0720 | Train Acc: 0.9727 | Train Precision: 0.9727 | Train Recall: 0.9727 | Train F1: 0.9727
Test Loss: 0.2788 | Test Acc: 0.9265 | Test Precision: 0.9303 | Test Recall: 0.9265 | Test F1: 0.9273

Epoch 17/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0670 | Train Acc: 0.9741 | Train Precision: 0.9741 | Train Recall: 0.9741 | Train F1: 0.9741
Test Loss: 0.2886 | Test Acc: 0.9321 | Test Precision: 0.9330 | Test Recall: 0.9321 | Test F1: 0.9323

Epoch 18/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0626 | Train Acc: 0.9763 | Train Precision: 0.9763 | Train Recall: 0.9763 | Train F1: 0.9763
Test Loss: 0.3031 | Test Acc: 0.9293 | Test Precision: 0.9301 | Test Recall: 0.9293 | Test F1: 0.9295

Epoch 19/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0621 | Train Acc: 0.9768 | Train Precision: 0.9768 | Train Recall: 0.9768 | Train F1: 0.9768
Test Loss: 0.2993 | Test Acc: 0.9298 | Test Precision: 0.9303 | Test Recall: 0.9298 | Test F1: 0.9300

Epoch 20/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.0571 | Train Acc: 0.9777 | Train Precision: 0.9777 | Train Recall: 0.9777 | Train F1: 0.9777
Test Loss: 0.3068 | Test Acc: 0.9309 | Test Precision: 0.9308 | Test Recall: 0.9309 | Test F1: 0.9308

In [10]:
from src.models import CNN
from src.train import train_step, test_step

epochs = 20
history = {
    "train": [],
    "test": []
}

exp4 = CNN(dropout=0.6).to(device)

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(
    params=exp4.parameters(),
    lr=0.0005
)

for epoch in range(epochs):
    print(f"\nEpoch {epoch+1}/{epochs}")
    print("-"*30)

    train_results = train_step(
        model=exp4,
        dataloader=train_dataloader,
        loss_fn=loss_fn,
        optimizer=optimizer,
        metrics=train_metrics,
        device=device
    )

    test_results = test_step(
        model=exp4,
        dataloader=test_dataloader,
        loss_fn=loss_fn,
        metrics=test_metrics,
        device=device
    )

    history["train"].append(train_results)
    history["test"].append(test_results)

    print(
        f"Train Loss: {train_results['loss']:.4f} | "
        f"Train Acc: {train_results['accuracy']:.4f} | "
        f"Train Precision: {train_results['precision']:.4f} | "
        f"Train Recall: {train_results['recall']:.4f} | "
        f"Train F1: {train_results['f1']:.4f}"
    )

    print(
        f"Test Loss: {test_results['loss']:.4f} | "
        f"Test Acc: {test_results['accuracy']:.4f} | "
        f"Test Precision: {test_results['precision']:.4f} | "
        f"Test Recall: {test_results['recall']:.4f} | "
        f"Test F1: {test_results['f1']:.4f}"
    )

exp_results.append({
    "dropout": 0.6,
    "train_loss": history["train"][-1]["loss"],
    "test_loss": history["test"][-1]["loss"],
    "train_accuracy": history["train"][-1]["accuracy"],
    "test_accuracy": history["test"][-1]["accuracy"],
    "train_precision": history["train"][-1]["precision"],
    "test_precision": history["test"][-1]["precision"],
    "train_recall": history["train"][-1]["recall"],
    "test_recall": history["test"][-1]["recall"],
    "train_f1": history["train"][-1]["f1"],
    "test_f1": history["test"][-1]["f1"]
})

Epoch 1/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.5905 | Train Acc: 0.7885 | Train Precision: 0.7855 | Train Recall: 0.7885 | Train F1: 0.7862
Test Loss: 0.3476 | Test Acc: 0.8721 | Test Precision: 0.8733 | Test Recall: 0.8721 | Test F1: 0.8702

Epoch 2/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.3933 | Train Acc: 0.8602 | Train Precision: 0.8591 | Train Recall: 0.8602 | Train F1: 0.8592
Test Loss: 0.2999 | Test Acc: 0.8905 | Test Precision: 0.8907 | Test Recall: 0.8905 | Test F1: 0.8885

Epoch 3/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.3426 | Train Acc: 0.8769 | Train Precision: 0.8760 | Train Recall: 0.8769 | Train F1: 0.8762
Test Loss: 0.2621 | Test Acc: 0.9036 | Test Precision: 0.9033 | Test Recall: 0.9036 | Test F1: 0.9034

Epoch 4/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.3051 | Train Acc: 0.8911 | Train Precision: 0.8903 | Train Recall: 0.8911 | Train F1: 0.8904
Test Loss: 0.2576 | Test Acc: 0.9037 | Test Precision: 0.9039 | Test Recall: 0.9037 | Test F1: 0.9036

Epoch 5/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2810 | Train Acc: 0.8986 | Train Precision: 0.8980 | Train Recall: 0.8986 | Train F1: 0.8982
Test Loss: 0.2420 | Test Acc: 0.9131 | Test Precision: 0.9131 | Test Recall: 0.9131 | Test F1: 0.9127

Epoch 6/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2572 | Train Acc: 0.9067 | Train Precision: 0.9063 | Train Recall: 0.9067 | Train F1: 0.9064
Test Loss: 0.2337 | Test Acc: 0.9161 | Test Precision: 0.9172 | Test Recall: 0.9161 | Test F1: 0.9159

Epoch 7/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2372 | Train Acc: 0.9129 | Train Precision: 0.9127 | Train Recall: 0.9129 | Train F1: 0.9127
Test Loss: 0.2297 | Test Acc: 0.9199 | Test Precision: 0.9198 | Test Recall: 0.9199 | Test F1: 0.9192

Epoch 8/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2209 | Train Acc: 0.9184 | Train Precision: 0.9183 | Train Recall: 0.9184 | Train F1: 0.9183
Test Loss: 0.2213 | Test Acc: 0.9225 | Test Precision: 0.9233 | Test Recall: 0.9225 | Test F1: 0.9228

Epoch 9/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2064 | Train Acc: 0.9230 | Train Precision: 0.9228 | Train Recall: 0.9230 | Train F1: 0.9229
Test Loss: 0.2239 | Test Acc: 0.9227 | Test Precision: 0.9226 | Test Recall: 0.9227 | Test F1: 0.9226

Epoch 10/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1952 | Train Acc: 0.9267 | Train Precision: 0.9265 | Train Recall: 0.9267 | Train F1: 0.9266
Test Loss: 0.2330 | Test Acc: 0.9204 | Test Precision: 0.9202 | Test Recall: 0.9204 | Test F1: 0.9199

Epoch 11/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1808 | Train Acc: 0.9329 | Train Precision: 0.9328 | Train Recall: 0.9329 | Train F1: 0.9328
Test Loss: 0.2387 | Test Acc: 0.9209 | Test Precision: 0.9215 | Test Recall: 0.9209 | Test F1: 0.9209

Epoch 12/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1688 | Train Acc: 0.9367 | Train Precision: 0.9366 | Train Recall: 0.9367 | Train F1: 0.9366
Test Loss: 0.2253 | Test Acc: 0.9291 | Test Precision: 0.9295 | Test Recall: 0.9291 | Test F1: 0.9291

Epoch 13/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1602 | Train Acc: 0.9387 | Train Precision: 0.9387 | Train Recall: 0.9387 | Train F1: 0.9387
Test Loss: 0.2280 | Test Acc: 0.9274 | Test Precision: 0.9278 | Test Recall: 0.9274 | Test F1: 0.9275

Epoch 14/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1518 | Train Acc: 0.9420 | Train Precision: 0.9420 | Train Recall: 0.9421 | Train F1: 0.9420
Test Loss: 0.2415 | Test Acc: 0.9264 | Test Precision: 0.9268 | Test Recall: 0.9264 | Test F1: 0.9265

Epoch 15/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1411 | Train Acc: 0.9455 | Train Precision: 0.9454 | Train Recall: 0.9455 | Train F1: 0.9454
Test Loss: 0.2489 | Test Acc: 0.9271 | Test Precision: 0.9270 | Test Recall: 0.9271 | Test F1: 0.9268

Epoch 16/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1357 | Train Acc: 0.9468 | Train Precision: 0.9467 | Train Recall: 0.9468 | Train F1: 0.9467
Test Loss: 0.2407 | Test Acc: 0.9265 | Test Precision: 0.9266 | Test Recall: 0.9265 | Test F1: 0.9264

Epoch 17/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1283 | Train Acc: 0.9502 | Train Precision: 0.9502 | Train Recall: 0.9502 | Train F1: 0.9502
Test Loss: 0.2458 | Test Acc: 0.9275 | Test Precision: 0.9278 | Test Recall: 0.9275 | Test F1: 0.9276

Epoch 18/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1217 | Train Acc: 0.9526 | Train Precision: 0.9527 | Train Recall: 0.9526 | Train F1: 0.9526
Test Loss: 0.2601 | Test Acc: 0.9301 | Test Precision: 0.9299 | Test Recall: 0.9301 | Test F1: 0.9299

Epoch 19/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1161 | Train Acc: 0.9535 | Train Precision: 0.9534 | Train Recall: 0.9534 | Train F1: 0.9534
Test Loss: 0.2746 | Test Acc: 0.9294 | Test Precision: 0.9295 | Test Recall: 0.9294 | Test F1: 0.9294

Epoch 20/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.1145 | Train Acc: 0.9546 | Train Precision: 0.9546 | Train Recall: 0.9546 | Train F1: 0.9546
Test Loss: 0.2671 | Test Acc: 0.9276 | Test Precision: 0.9286 | Test Recall: 0.9276 | Test F1: 0.9278

In [11]:
from src.models import CNN
from src.train import train_step, test_step

epochs = 20
history = {
    "train": [],
    "test": []
}

exp5 = CNN(dropout=0.8).to(device)

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(
    params=exp5.parameters(),
    lr=0.0005
)

for epoch in range(epochs):
    print(f"\nEpoch {epoch+1}/{epochs}")
    print("-"*30)

    train_results = train_step(
        model=exp5,
        dataloader=train_dataloader,
        loss_fn=loss_fn,
        optimizer=optimizer,
        metrics=train_metrics,
        device=device
    )

    test_results = test_step(
        model=exp5,
        dataloader=test_dataloader,
        loss_fn=loss_fn,
        metrics=test_metrics,
        device=device
    )

    history["train"].append(train_results)
    history["test"].append(test_results)

    print(
        f"Train Loss: {train_results['loss']:.4f} | "
        f"Train Acc: {train_results['accuracy']:.4f} | "
        f"Train Precision: {train_results['precision']:.4f} | "
        f"Train Recall: {train_results['recall']:.4f} | "
        f"Train F1: {train_results['f1']:.4f}"
    )

    print(
        f"Test Loss: {test_results['loss']:.4f} | "
        f"Test Acc: {test_results['accuracy']:.4f} | "
        f"Test Precision: {test_results['precision']:.4f} | "
        f"Test Recall: {test_results['recall']:.4f} | "
        f"Test F1: {test_results['f1']:.4f}"
    )

exp_results.append({
    "dropout": 0.8,
    "train_loss": history["train"][-1]["loss"],
    "test_loss": history["test"][-1]["loss"],
    "train_accuracy": history["train"][-1]["accuracy"],
    "test_accuracy": history["test"][-1]["accuracy"],
    "train_precision": history["train"][-1]["precision"],
    "test_precision": history["test"][-1]["precision"],
    "train_recall": history["train"][-1]["recall"],
    "test_recall": history["test"][-1]["recall"],
    "train_f1": history["train"][-1]["f1"],
    "test_f1": history["test"][-1]["f1"]
})

Epoch 1/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.8356 | Train Acc: 0.6846 | Train Precision: 0.6773 | Train Recall: 0.6846 | Train F1: 0.6799
Test Loss: 0.3982 | Test Acc: 0.8593 | Test Precision: 0.8565 | Test Recall: 0.8593 | Test F1: 0.8556

Epoch 2/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.6124 | Train Acc: 0.7622 | Train Precision: 0.7591 | Train Recall: 0.7622 | Train F1: 0.7601
Test Loss: 0.3453 | Test Acc: 0.8776 | Test Precision: 0.8762 | Test Recall: 0.8776 | Test F1: 0.8756

Epoch 3/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.5436 | Train Acc: 0.7913 | Train Precision: 0.7909 | Train Recall: 0.7913 | Train F1: 0.7908
Test Loss: 0.3093 | Test Acc: 0.8898 | Test Precision: 0.8902 | Test Recall: 0.8898 | Test F1: 0.8872

Epoch 4/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.4988 | Train Acc: 0.8079 | Train Precision: 0.8076 | Train Recall: 0.8079 | Train F1: 0.8074
Test Loss: 0.2865 | Test Acc: 0.8977 | Test Precision: 0.8974 | Test Recall: 0.8977 | Test F1: 0.8961

Epoch 5/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.4685 | Train Acc: 0.8176 | Train Precision: 0.8175 | Train Recall: 0.8176 | Train F1: 0.8169
Test Loss: 0.2747 | Test Acc: 0.9028 | Test Precision: 0.9019 | Test Recall: 0.9028 | Test F1: 0.9014

Epoch 6/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.4466 | Train Acc: 0.8282 | Train Precision: 0.8282 | Train Recall: 0.8282 | Train F1: 0.8273
Test Loss: 0.2635 | Test Acc: 0.9069 | Test Precision: 0.9061 | Test Recall: 0.9069 | Test F1: 0.9058

Epoch 7/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.4163 | Train Acc: 0.8379 | Train Precision: 0.8383 | Train Recall: 0.8379 | Train F1: 0.8375
Test Loss: 0.2536 | Test Acc: 0.9115 | Test Precision: 0.9115 | Test Recall: 0.9115 | Test F1: 0.9114

Epoch 8/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.4084 | Train Acc: 0.8398 | Train Precision: 0.8407 | Train Recall: 0.8398 | Train F1: 0.8396
Test Loss: 0.2483 | Test Acc: 0.9127 | Test Precision: 0.9127 | Test Recall: 0.9127 | Test F1: 0.9121

Epoch 9/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.3868 | Train Acc: 0.8490 | Train Precision: 0.8507 | Train Recall: 0.8491 | Train F1: 0.8492
Test Loss: 0.2453 | Test Acc: 0.9140 | Test Precision: 0.9144 | Test Recall: 0.9140 | Test F1: 0.9138

Epoch 10/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.3735 | Train Acc: 0.8529 | Train Precision: 0.8544 | Train Recall: 0.8529 | Train F1: 0.8529
Test Loss: 0.2441 | Test Acc: 0.9156 | Test Precision: 0.9158 | Test Recall: 0.9156 | Test F1: 0.9144

Epoch 11/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.3598 | Train Acc: 0.8593 | Train Precision: 0.8605 | Train Recall: 0.8593 | Train F1: 0.8593
Test Loss: 0.2309 | Test Acc: 0.9222 | Test Precision: 0.9220 | Test Recall: 0.9222 | Test F1: 0.9218

Epoch 12/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.3518 | Train Acc: 0.8638 | Train Precision: 0.8655 | Train Recall: 0.8638 | Train F1: 0.8641
Test Loss: 0.2402 | Test Acc: 0.9172 | Test Precision: 0.9171 | Test Recall: 0.9172 | Test F1: 0.9170

Epoch 13/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.3402 | Train Acc: 0.8677 | Train Precision: 0.8690 | Train Recall: 0.8677 | Train F1: 0.8678
Test Loss: 0.2272 | Test Acc: 0.9228 | Test Precision: 0.9232 | Test Recall: 0.9228 | Test F1: 0.9229

Epoch 14/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.3295 | Train Acc: 0.8706 | Train Precision: 0.8719 | Train Recall: 0.8707 | Train F1: 0.8707
Test Loss: 0.2318 | Test Acc: 0.9219 | Test Precision: 0.9214 | Test Recall: 0.9219 | Test F1: 0.9214

Epoch 15/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.3190 | Train Acc: 0.8756 | Train Precision: 0.8768 | Train Recall: 0.8756 | Train F1: 0.8756
Test Loss: 0.2270 | Test Acc: 0.9218 | Test Precision: 0.9215 | Test Recall: 0.9218 | Test F1: 0.9214

Epoch 16/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.3072 | Train Acc: 0.8811 | Train Precision: 0.8824 | Train Recall: 0.8811 | Train F1: 0.8812
Test Loss: 0.2325 | Test Acc: 0.9196 | Test Precision: 0.9193 | Test Recall: 0.9196 | Test F1: 0.9191

Epoch 17/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.3008 | Train Acc: 0.8821 | Train Precision: 0.8832 | Train Recall: 0.8821 | Train F1: 0.8821
Test Loss: 0.2293 | Test Acc: 0.9231 | Test Precision: 0.9226 | Test Recall: 0.9231 | Test F1: 0.9226

Epoch 18/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2917 | Train Acc: 0.8848 | Train Precision: 0.8857 | Train Recall: 0.8848 | Train F1: 0.8848
Test Loss: 0.2211 | Test Acc: 0.9244 | Test Precision: 0.9247 | Test Recall: 0.9244 | Test F1: 0.9244

Epoch 19/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2861 | Train Acc: 0.8895 | Train Precision: 0.8905 | Train Recall: 0.8895 | Train F1: 0.8895
Test Loss: 0.2331 | Test Acc: 0.9219 | Test Precision: 0.9228 | Test Recall: 0.9219 | Test F1: 0.9216

Epoch 20/20
------------------------------
Looked at 0 / 60000 samples
Looked at 12800 / 60000 samples
Looked at 25600 / 60000 samples
Looked at 38400 / 60000 samples
Looked at 51200 / 60000 samples
Train Loss: 0.2776 | Train Acc: 0.8913 | Train Precision: 0.8923 | Train Recall: 0.8913 | Train F1: 0.8913
Test Loss: 0.2288 | Test Acc: 0.9266 | Test Precision: 0.9264 | Test Recall: 0.9266 | Test F1: 0.9262

In [21]:
df = pd.DataFrame(exp_results)
df = df.sort_values(
    by=["dropout"],
    ascending=[True]
)
df

,dropout,train_loss,test_loss,train_accuracy,test_accuracy,train_precision,test_precision,train_recall,test_recall,train_f1,test_f1
5,0.0,0.008142,0.541725,0.997067,0.9227,0.997066,0.923460,0.997067,0.9227,0.997066,0.923008
0,0.2,0.028744,0.413835,0.989233,0.9270,0.989231,0.926999,0.989233,0.9270,0.989231,0.926772
1,0.4,0.054595,0.321659,0.978517,0.9275,0.978495,0.927471,0.978517,0.9275,0.978491,0.927437
2,0.5,0.057100,0.306810,0.977733,0.9309,0.977722,0.930795,0.977733,0.9309,0.977725,0.930805
3,0.6,0.114456,0.267079,0.954567,0.9276,0.954624,0.928588,0.954567,0.9276,0.954583,0.927804
4,0.8,0.277591,0.228771,0.891300,0.9266,0.892273,0.926398,0.891300,0.9266,0.891295,0.926230

In [22]:
new_df = df[['dropout', 'train_loss', 'test_loss', 'train_accuracy', 'test_accuracy']]

new_df

   dropout  train_loss  test_loss  train_accuracy  test_accuracy
5      0.0    0.008142   0.541725        0.997067         0.9227
0      0.2    0.028744   0.413835        0.989233         0.9270
1      0.4    0.054595   0.321659        0.978517         0.9275
2      0.5    0.057100   0.306810        0.977733         0.9309
3      0.6    0.114456   0.267079        0.954567         0.9276
4      0.8    0.277591   0.228771        0.891300         0.9266